### PR TITLE
Fixes for ruby 2.7

### PR DESCRIPTION
**Pull request by zenspider**
This addresses a lot of warnings coming from the code. Found via our use of tomlrb, but also apparent in the tests themselves. I fixed up the generated parser and minitest tests while I was in there so now it should be warning free.

### CODE REVIEW

**Comment by fbernier** [comment]
Hey thanks! This project needs some love and that help a lot. I guess I should look at the 0.5.0 spec at some point.

**Comment by zenspider** [comment]
Fantastic. Thank you!

**Comment by zenspider** [comment]
... I imagine toml 0.5.0 work will be a while out... is there any chance I can agitate for a release with just these fixes before that tangent gets completed?

**Comment by fbernier** [comment]
@zenspider sure, 1.2.9 has been published :tada:

**Pull request merged**
