### PR TITLE
Add support for day only and datetime without offset

### PR DESCRIPTION
**Pull request by cedarvera**
I used the recommend defaults for time as 00:00:00 and offset as machine local from https://github.com/toml-lang/toml#user-content-datetime

### CODE REVIEW

**Comment by fbernier** [comment]
Thanks for the pull request and sorry I just noticed it! Will review asap.

**Comment by fbernier** [comment]
Any idea what made lib/tomlrb/generated_parser.rb change?

**Comment by cedarvera** [comment]
Not sure.  It looks like it does the same changes the generated_parser.rb when I ran rake compile before my commits.  I tried it with racc 1.4.13 and 1.4.14.

**Comment by fbernier** [comment]
Hhhm weird for me it's the opposite. Pulling in your changes and running `rake compile` reverts your changes to it, even on 1.4.14. Will investigate but for now it does not seem to affect any tests. Ruby 2.3.1?

**Comment by cedarvera** [comment]
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin13]

**Comment by fbernier** [comment]
Released 1.2.2

**Pull request merged**
