### PR TITLE
Fixes #20 TOML 1.0.0-rc3

### LINKED ISSUE #20: update parser to TOML v0.5.0 specification
Citation from [toml repository](https://github.com/toml-lang/toml):

> As of version 0.5.0, TOML should be considered extremely stable. The goal is for version 1.0.0 to be backwards compatible (as much as humanly possible) with version 0.5.0. **All implementations are strongly encouraged to become 0.5.0 compatible** so that the transition to 1.0.0 will be simple when that happens.

I think we need the following features for adapting to v0.5.0:

### Handle `inf` and `nan` expression

> Special float values can also be expressed. They are always lowercase.

```toml
# infinity
sf1 = inf  # positive infinity
sf2 = +inf # positive infinity
sf3 = -inf # negative infinity

# not a number
sf4 = nan  # actual sNaN/qNaN encoding is implementation specific
sf5 = +nan # same as `nan`
sf6 = -nan # valid, actual encoding is implementation specific
```

### Local Date-Time, Local Date, Local Time

These features may need defining new classes for implementation, since the instances of `Time` or `Date` provided by built-in/standard library have their timezones.

#### Local Date-Time

> If you omit the offset from an RFC 3339 formatted date-time, it will represent the given date-time **without any relation to an offset or timezone**. It cannot be converted to an instant in time without additional information. Conversion to an instant, if required, is implementation specific.

#### Local Date

> If you include only the date portion of an RFC 3339 formatted date-time, it will represent that entire day without any relation to an offset or timezone.

#### Local Time

> If you include only the time portion of an RFC 3339 formatted date-time, it will represent that time of day without any relation to a specific day or any offset or timezone.

### PR DESCRIPTION
**Pull request by KitaitiMakoto**
Hi,

This patch supports TOML 1.0.0-rc3.

### CODE REVIEW

**Comment by fbernier** [comment]
Thanks for all this work! :clap:  Let me know when you want to cut a release.

**Comment by KitaitiMakoto** [comment]
@fbernier I think it' ready to release. But I want to ask your versioning policy. This patch introduces a breaking change that strings like `2020-11-23 13:23:00` is converted to `Tomlrb::LocalDateTime` instead of `String`. Is it better to release a candidate version and warn the change to existing users?

**Comment by fbernier** [comment]
@KitaitiMakoto I think putting a `breaking changes` section in the changelog and bumping to a major version, just like the spec did, should be enough.

**Comment by KitaitiMakoto** [comment]
@fbernier Okay, I will write changelog later.

**Pull request merged**
